services:
  - type: web
    name: azure-tobacco-api
    env: node
    plan: free
    rootDir: src/components/src/backend
    buildCommand: npm install
    startCommand: npm start
    dockerCommand: ""
    dockerfilePath: ""
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: DB_PATH
        value: ./database/orders.db
